# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 
email: heysid3@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog which contains a lot of gibberish or useful things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://undefined.nz" # the base hostname & protocol for your site
github_username: skia92
permalink: /blog/:year/:month/:day/:title/

# Build settings
markdown: kramdown
