#
###################################
# Site wide configuration
####################################
#
title: Vincent Choe
email: heysid3@gmail.com
description: 개발 지식 공간
#url: https://renyuanz.github.io/leonids # the base hostname & protocol for your site
keywords: ["Programming"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          America/Los_Angeles
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Vincent Choe
  avatar: logo.jpg
  job: "Software Developer"
  bio: "A developer who always seeks new things"
  email: heysid3@gmail.com
  disqus-shortname: skia92-github-io
  twitter: #username
  facebook: #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: skia92 #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username
